server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: order
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json

api:
  url:
    pay: http://localhost:8086/payments
    seat: http://localhost:8082
---
spring:
  profiles: docker
#  sleuth:
#    sampler:
#      probability: 1
#    web:
#      skipPattern: (^cleanup.*|.+favicon.*)
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        input:
          group: order
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json

api:
  url:
    gateway5: http://gateway5:8080
    seat5: http://seat5:8080
    payment5: http://payment5:8080
