server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        input:
          group: order
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
        input:
          group: order
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json
cloud:
    gateway:
      routes:
       - id: product
         uri: http://payment5:8080
